version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/opencars/vin-decoder-api
    steps:
      - checkout

      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: "Install Dependencies"
          command: "go mod download"

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: "Run Tests"
          command: "go test -v -bench=. -race ./..."

      - run:
          name: "Lint Code"
          environment:
            GO111MODULE: "off"
          command: |
            go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
            GO111MODULE=on golangci-lint run

      - run:
          name: Build Project Binary
          command: |
            go build -o ./bin/server ./cmd/server/main.go

  release:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "off"
          USER_NAME: "Ali Shanaakh"
          USER_EMAIL: "github@shal.dev"
    steps:
      - checkout

      - run:
          name: "Set Git Configuration"
          command: |
            git config --global user.name "${USER_NAME}"
            git config --global user.email "${USER_EMAIL}"

      - run:
          name: "Bump Version"
          command: |
            go get github.com/Clever/gitsem
            gitsem -m "[ci skip] Bump version to %s" patch

      - run:
          name: "Release Version"
          command: |
            git remote add authenticated-origin https://${GITHUB_USER}:${GITHUB_API_KEY}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            git push --tags authenticated-origin HEAD:${CIRCLE_BRANCH}
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: "Login to quay.io"
          command: |
            docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD} quay.io

      - run:
          name: "Build Docker Image"
          command: |
            docker build -t quay.io/opencars/vin-decoder-api:${CIRCLE_TAG} .
            docker build -t quay.io/opencars/vin-decoder-api .

      - run:
          name: "Push Docker Image"
          command: |
            docker push quay.io/opencars/vin-decoder-api:${CIRCLE_TAG}
            docker push quay.io/opencars/vin-decoder-api
workflows:
  version: 2
  test-relase-build:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/